name: Continuous Deployment

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: The type of release. Should be one of "major", "minor", "patch"
        required: true
        default: 'patch'
  pull_request:
    branches:
      - main

# Make sure we're not running multiple release steps at the same time as this can give issues with determining the next npm version to release.
# Ideally we only add this to the 'release' job so it doesn't limit PR runs, but github can't guarantee the job order in that case:
# "When concurrency is specified at the job level, order is not guaranteed for jobs or runs that queue within 5 minutes of each other."
concurrency:
  group: react-native-ble-didcomm${{ github.ref }}-${{ github.repository }}-{{ github.event_name }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-20.04
    name: Validate
    steps:
      - name: Checkout react-native-ble-didcomm
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.15.4

      - name: Setup node v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: lint
        run: pnpm run check

      - name: Check typescript
        run: pnpm run check:types

  release:
    runs-on: ubuntu-20.04
    name: Release
    needs: [validate]
    # Only run on workflow dispatch to main branch
    if: github.ref == 'refs/heads/main' && github.repository == 'animo/react-native-ble-didcomm' && github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout react-native-ble-didcomm
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: git config
        run: |
          git config user.name "@github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.15.4

      - name: Setup node v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install

      - name: Set Verbose Logging
        run: pnpm config set loglevel verbose --global

      - name: Set NPM config
        run: |
          echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN }}" >> .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "always-auth=true" >> .npmrc

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build the library
        run: pnpm run build

      - name: Release version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm run release ${{ github.event.inputs.releaseType }}
